name: Deploy CloudFormation Template

on:
  workflow_dispatch:
    inputs:
      instance_count:
        description: 'Number of instances'
        required: true
        default: '1'
      instance_type:
        type: choice
        description: 'EC2 Instance Type'
        required: true
        default: 't2.micro'
        options:
        - t2.micro
        - t2.xlarge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file path/to/your/template.yaml \
            --stack-name your-stack-name \
            --parameter-overrides \
              InstanceCount=${{ github.event.inputs.instance_count }} \
              InstanceType=${{ github.event.inputs.instance_type }} \
            --capabilities CAPABILITY_IAM

      - name: Output result
        run: echo "Deployment completed"
