name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose which action to perform on the cloudformation template"
        default: "create"
        options:
        - create
        - update
        - delete

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.action }}"
