name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose which action to perform on the cloudformation template"
        type: choice
        default: "create"
        options:
        - create
        - update
        - delete

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          if: ${{github.event.inputs.action == 'create'}}
          run: echo "Hello ${{ github.event.inputs.action }}"
          
        steps:
        - name: Hello Step1
          if: ${{github.event.inputs.action == 'delete'}}
          run: echo "Hello ${{ github.event.inputs.action }}"

        steps:
        - name: Hello Step2
          if: ${{github.event.inputs.action == 'update'}}
          run: echo "Hello ${{ github.event.inputs.action }}"
